version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Update Debian package repositories
          command: |
            sudo sed -i '/stretch-updates/d' /etc/apt/sources.list
            sudo sed -i '/stretch/d' /etc/apt/sources.list
            sudo apt-get update
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t my-app .
      - run:
          name: Push Docker image to DockerHub
          command: |
            docker login -u shwetha1990 -p Welcome123
            docker tag my-app shwetha1990/my-app
            docker push shwetha1990/my-app

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: main

